[workspace]
resolver = "3"
members = ["spinal"]
exclude = ["bevy_spinal"]

[workspace.package]
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gak/spinal"

[workspace.dependencies]
glam = { version = "0.30.10", default-features = false, features = ["std"] }
thiserror = "2.0.19"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
