[workspace]
resolver = "3"
members = ["bevy_spinal", "spinal"]
exclude = ["fuzz"]

[workspace.package]
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gak/spinal"

[workspace.dependencies]
bevy = { version = "0.18.1", default-features = false }
glam = { version = "0.30.10", default-features = false, features = ["std"] }
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.18"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
