[graph]
all-features = true

[advisories]
version = 2
yanked = "deny"
ignore = []
unmaintained = "workspace"

[licenses]
version = 2
confidence-threshold = 0.93
include-dev = true
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
