use std::f32::consts::{PI, TAU};

use bevy::math::Vec2;
use serde_json::Value;
use thiserror::Error;

use super::{json_document::TranslationKey, rig::RigBinding};

pub(crate) const WALK_SAMPLES: usize = 16;
const STANCE_FRACTION: f32 = 0.625;
const NATIVE_GROUND_SPEED: f32 = 40.0;
const BODY_LOWERING: f32 = 10.0;

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct WalkParameters {
    pub(crate) stride: f32,
    pub(crate) lift: f32,
    pub(crate) bob: f32,
}

impl Default for WalkParameters {
    fn default() -> Self {
        Self {
            stride: 20.0,
            lift: 12.0,
            bob: 2.0,
        }
    }
}

impl WalkParameters {
    pub(crate) fn clamp(&mut self) {
        self.stride = self.stride.clamp(4.0, 40.0);
        self.lift = self.lift.clamp(0.0, 24.0);
        self.bob = self.bob.clamp(0.0, 8.0);
    }

    /// Samples the piecewise-linear curve that is written to JSON.
    pub(crate) fn sample_preview(self, time: f32) -> WalkPose {
        let sample_position = (time / self.duration()).rem_euclid(1.0) * WALK_SAMPLES as f32;
        let first = sample_position.floor() as usize;
        let mix = sample_position - first as f32;
        let first_pose = self.sample_cycle(first as f32 / WALK_SAMPLES as f32);
        let second_pose = self.sample_cycle((first + 1) as f32 / WALK_SAMPLES as f32);
        first_pose.lerp(second_pose, mix)
    }

    pub(crate) fn duration(self) -> f32 {
        self.stride / (NATIVE_GROUND_SPEED * STANCE_FRACTION)
    }

    fn sample_cycle(self, cycle: f32) -> WalkPose {
        let cycle = cycle.rem_euclid(1.0);
        WalkPose {
            controls: [
                self.sample_paw(cycle),
                self.sample_paw((cycle + 0.75).fract()),
                self.sample_paw((cycle + 0.50).fract()),
                self.sample_paw((cycle + 0.25).fract()),
            ],
            body: Vec2::new(0.0, -BODY_LOWERING + self.bob * (2.0 * TAU * cycle).cos()),
        }
    }

    pub(crate) fn keys(self) -> [Vec<TranslationKey>; 5] {
        let mut output: [Vec<TranslationKey>; 5] =
            std::array::from_fn(|_index| Vec::with_capacity(WALK_SAMPLES + 1));
        for sample in 0..=WALK_SAMPLES {
            let time = self.duration() * sample as f32 / WALK_SAMPLES as f32;
            let pose = if sample == WALK_SAMPLES {
                self.sample_cycle(0.0)
            } else {
                self.sample_cycle(sample as f32 / WALK_SAMPLES as f32)
            };
            for (keys, offset) in output.iter_mut().take(4).zip(pose.controls) {
                keys.push(TranslationKey {
                    time,
                    x: offset.x,
                    y: offset.y,
                });
            }
            output[4].push(TranslationKey {
                time,
                x: pose.body.x,
                y: pose.body.y,
            });
        }
        output
    }

    fn sample_paw(self, phase: f32) -> Vec2 {
        let half_stride = self.stride * 0.5;
        if phase <= STANCE_FRACTION {
            let progress = phase / STANCE_FRACTION;
            Vec2::new(half_stride - self.stride * progress, 0.0)
        } else {
            let progress = (phase - STANCE_FRACTION) / (1.0 - STANCE_FRACTION);
            Vec2::new(
                -half_stride + self.stride * progress,
                self.lift * (PI * progress).sin(),
            )
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct WalkPose {
    pub(crate) controls: [Vec2; 4],
    pub(crate) body: Vec2,
}

impl WalkPose {
    fn lerp(self, other: Self, mix: f32) -> Self {
        Self {
            controls: std::array::from_fn(|index| {
                self.controls[index].lerp(other.controls[index], mix)
            }),
            body: self.body.lerp(other.body, mix),
        }
    }
}

#[derive(Debug, Error, PartialEq)]
pub(crate) enum ExistingWalkError {
    #[error("JSON could not be inspected for an existing animation: {0}")]
    InvalidJson(String),
    #[error(
        "animation `{0}` already contains keys that were not generated by this mini animator; choose another name with --animation"
    )]
    ForeignAnimation(String),
}

pub(crate) fn parameters_from_source(
    source: &str,
    animation_name: &str,
    binding: &RigBinding,
) -> Result<Option<WalkParameters>, ExistingWalkError> {
    let document: Value = serde_json::from_str(source)
        .map_err(|error| ExistingWalkError::InvalidJson(error.to_string()))?;
    let Some(animation) = document
        .get("animations")
        .and_then(|animations| animations.get(animation_name))
    else {
        return Ok(None);
    };
    if animation.as_object().is_some_and(serde_json::Map::is_empty) {
        return Ok(None);
    }

    let names = binding
        .controls
        .iter()
        .map(|control| control.name.as_ref())
        .chain(std::iter::once(binding.body.name.as_ref()))
        .collect::<Vec<_>>();
    let Some(bones) = animation
        .as_object()
        .filter(|animation| animation.len() == 1)
        .and_then(|animation| animation.get("bones"))
        .and_then(Value::as_object)
        .filter(|bones| bones.len() == names.len())
    else {
        return Err(ExistingWalkError::ForeignAnimation(
            animation_name.to_owned(),
        ));
    };
    let mut actual = Vec::with_capacity(names.len());
    for name in &names {
        let Some(frames) = bones
            .get(*name)
            .and_then(Value::as_object)
            .filter(|bone| bone.len() == 1)
            .and_then(|bone| bone.get("translate"))
            .and_then(Value::as_array)
        else {
            return Err(ExistingWalkError::ForeignAnimation(
                animation_name.to_owned(),
            ));
        };
        let parsed = parse_frames(frames)
            .ok_or_else(|| ExistingWalkError::ForeignAnimation(animation_name.to_owned()))?;
        actual.push(parsed);
    }

    let stride = actual[0][0].x * 2.0;
    let lift = actual[..4]
        .iter()
        .flat_map(|timeline| timeline.iter().map(|key| key.y))
        .fold(0.0_f32, f32::max);
    let body_min = actual[4]
        .iter()
        .map(|key| key.y)
        .fold(f32::INFINITY, f32::min);
    let body_max = actual[4]
        .iter()
        .map(|key| key.y)
        .fold(f32::NEG_INFINITY, f32::max);
    let parameters = WalkParameters {
        stride,
        lift,
        bob: (body_max - body_min) * 0.5,
    };
    let expected = parameters.keys();
    if actual
        .iter()
        .zip(expected.iter())
        .all(|(actual, expected)| matching_keys(actual, expected))
    {
        Ok(Some(parameters))
    } else {
        Err(ExistingWalkError::ForeignAnimation(
            animation_name.to_owned(),
        ))
    }
}

fn parse_frames(frames: &[Value]) -> Option<Vec<TranslationKey>> {
    if frames.len() != WALK_SAMPLES + 1 {
        return None;
    }
    frames
        .iter()
        .enumerate()
        .map(|(index, frame)| {
            let frame = frame.as_object()?;
            if frame
                .keys()
                .any(|key| !matches!(key.as_str(), "time" | "x" | "y"))
            {
                return None;
            }
            Some(TranslationKey {
                time: frame.get("time").map_or(Some(0.0), number_as_f32)?,
                x: number_as_f32(frame.get("x")?)?,
                y: number_as_f32(frame.get("y")?)?,
            })
            .filter(|key| index != 0 || key.time == 0.0)
        })
        .collect()
}

fn number_as_f32(value: &Value) -> Option<f32> {
    let number = value.as_f64()? as f32;
    number.is_finite().then_some(number)
}

fn matching_keys(actual: &[TranslationKey], expected: &[TranslationKey]) -> bool {
    actual.len() == expected.len()
        && actual.iter().zip(expected).all(|(actual, expected)| {
            (actual.time - expected.time).abs() < 1.0e-4
                && (actual.x - expected.x).abs() < 1.0e-3
                && (actual.y - expected.y).abs() < 1.0e-3
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        json_document::{TranslationTimeline, encode_translation_animation, upsert_animation},
        rig::ControlBinding,
    };
    use spinal::BoneTransform;

    fn assert_near(actual: f32, expected: f32) {
        assert!(
            (actual - expected).abs() < 1.0e-4,
            "expected {expected}, got {actual}"
        );
    }

    #[test]
    fn default_stance_cancels_twenty_pixels_of_root_travel() {
        let walk = WalkParameters::default();
        let start = walk.sample_cycle(0.0).controls[0];
        let end = walk.sample_cycle(STANCE_FRACTION).controls[0];

        assert_near(start.x, 10.0);
        assert_near(end.x, -10.0);
        assert_near(start.y, 0.0);
        assert_near(end.y, 0.0);
    }

    #[test]
    fn generated_keys_close_the_loop_exactly() {
        let keys = WalkParameters::default().keys();
        for timeline in keys {
            assert_eq!(timeline.len(), WALK_SAMPLES + 1);
            assert_eq!(
                timeline.first().map(|key| (key.x, key.y)),
                timeline.last().map(|key| (key.x, key.y))
            );
            assert_near(
                timeline.last().expect("closing key").time,
                WalkParameters::default().duration(),
            );
        }
    }

    #[test]
    fn paws_contact_in_the_intended_four_beat_order() {
        let walk = WalkParameters::default();
        for (index, cycle) in [0.0, 0.25, 0.5, 0.75].into_iter().enumerate() {
            let paw = walk.sample_cycle(cycle).controls[index];
            assert_near(paw.x, 10.0);
            assert_near(paw.y, 0.0);
        }
    }

    #[test]
    fn stride_changes_cycle_duration_to_preserve_ground_speed() {
        let short = WalkParameters {
            stride: 10.0,
            ..WalkParameters::default()
        };
        let long = WalkParameters {
            stride: 30.0,
            ..WalkParameters::default()
        };

        assert_near(short.duration(), 0.4);
        assert_near(long.duration(), 1.2);
        assert_near(
            short.stride / (short.duration() * STANCE_FRACTION),
            NATIVE_GROUND_SPEED,
        );
        assert_near(
            long.stride / (long.duration() * STANCE_FRACTION),
            NATIVE_GROUND_SPEED,
        );
    }

    #[test]
    fn preview_uses_the_same_linear_interpolation_as_written_keys() {
        let walk = WalkParameters::default();
        let keys = walk.keys();
        let time = walk.duration() * 0.5 / WALK_SAMPLES as f32;
        let preview = walk.sample_preview(time);

        for (control, timeline) in preview.controls.iter().zip(&keys[..4]) {
            assert_near(control.x, (timeline[0].x + timeline[1].x) * 0.5);
            assert_near(control.y, (timeline[0].y + timeline[1].y) * 0.5);
        }
        assert_near(preview.body.x, (keys[4][0].x + keys[4][1].x) * 0.5);
        assert_near(preview.body.y, (keys[4][0].y + keys[4][1].y) * 0.5);
    }

    #[test]
    fn generated_walk_parameters_can_be_reopened_without_owning_other_clips() {
        let binding = test_binding();
        let parameters = WalkParameters {
            stride: 24.0,
            lift: 14.0,
            bob: 3.0,
        };
        let keys = parameters.keys();
        let names = binding
            .controls
            .iter()
            .map(|control| control.name.as_ref())
            .chain(std::iter::once(binding.body.name.as_ref()))
            .collect::<Vec<_>>();
        let timelines = names
            .iter()
            .zip(&keys)
            .map(|(bone, keys)| TranslationTimeline { bone, keys })
            .collect::<Vec<_>>();
        let encoded = encode_translation_animation(&timelines).unwrap();
        let source = upsert_animation("{\"animations\":{}}", "walk", &encoded).unwrap();

        assert_eq!(
            parameters_from_source(&source, "walk", &binding),
            Ok(Some(parameters))
        );
        assert_eq!(
            parameters_from_source(
                "{\"animations\":{\"walk\":{\"bones\":{\"head\":{}}}}}",
                "walk",
                &binding
            ),
            Err(ExistingWalkError::ForeignAnimation("walk".to_owned()))
        );
    }

    fn test_binding() -> RigBinding {
        let control = |name: &str| ControlBinding {
            name: name.into(),
            setup: BoneTransform::IDENTITY,
        };
        RigBinding {
            controls: [control("a"), control("b"), control("c"), control("d")],
            body: control("body"),
        }
    }
}
