[package]
name = "spinal-viewer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
accesskit = "0.21.1"
bevy = { workspace = true, features = [
    "2d_bevy_render",
    "bevy_asset",
    "bevy_camera",
    "bevy_color",
    "bevy_image",
    "bevy_input_focus",
    "bevy_sprite",
    "bevy_ui",
    "bevy_ui_render",
    "bevy_winit",
    "default_app",
    "default_font",
    "multi_threaded",
    "png",
    "std",
    "x11",
] }
bevy_spinal = { path = "../../bevy_spinal", version = "0.1.0", default-features = false, features = ["render"] }

[lints]
workspace = true
